import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import '../../providers/cart_provider.dart';
import '../../providers/user_provider.dart';
import '../../providers/auth_provider.dart';
import '../../models/order_model.dart';
import '../../services/order_service.dart';
import '../../services/payment_service.dart';
import '../../constants/app_colors.dart';
import '../../utils/currency_formatter.dart';
import 'order_confirmation_screen.dart';
import 'sslcommerz_webview_screen.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class CheckoutScreen extends StatefulWidget {
  const CheckoutScreen({super.key});

  @override
  State<CheckoutScreen> createState() => _CheckoutScreenState();
}

class _CheckoutScreenState extends State<CheckoutScreen> {
  final OrderService _orderService = OrderService();
  final PaymentService _paymentService = PaymentService();
  bool _isProcessing = false;

  void _processCheckout(BuildContext context) async {
    final cartProvider = context.read<CartProvider>();
    final userProvider = context.read<UserProvider>();
    final authProvider = context.read<AuthProvider>();

    final user = userProvider.userProfile;
    final userId = authProvider.user?.uid;

    if (user == null || userId == null || cartProvider.items.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Invalid checkout state.')),
      );
      return;
    }

    setState(() {
      _isProcessing = true;
    });

    try {
      // 0. Verify stock
      for (var item in cartProvider.items) {
        final productDoc = await FirebaseFirestore.instance.collection('products').doc(item.productId).get();
        if (!productDoc.exists) {
          if (!context.mounted) return;
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Some items are no longer available. Please update your cart.')),
          );
          setState(() {
            _isProcessing = false;
          });
          return;
        }
        
        final maxStock = (productDoc.data() as Map<String, dynamic>)['stockQuantity'] ?? 0;
        if (item.quantity > maxStock) {
          if (!context.mounted) return;
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Some items are no longer available in the selected quantity.')),
          );
          setState(() {
            _isProcessing = false;
          });
          return;
        }
      }

      // 1. Create order in Firestore
      final sellerId = cartProvider.items.first.sellerId;
      final order = OrderModel(
        id: '', // Will be generated by service
        userId: userId,
        sellerId: sellerId,
        items: cartProvider.items.map((e) => e.toMap()).toList(),
        totalAmount: cartProvider.totalPrice,
        status: 'pending_payment',
        paymentMethod: 'sslcommerz',
        createdAt: DateTime.now(),
        buyerName: user.name,
        buyerEmail: user.email,
        buyerPhone: user.phoneNumber,
      );

      final orderId = await _orderService.createOrder(order);
      
      // Update order object with the generated ID for the payment service
      final orderWithId = OrderModel(
        id: orderId,
        userId: order.userId,
        sellerId: order.sellerId,
        items: order.items,
        totalAmount: order.totalAmount,
        status: order.status,
        paymentMethod: order.paymentMethod,
        createdAt: order.createdAt,
        buyerName: order.buyerName,
        buyerEmail: order.buyerEmail,
        buyerPhone: order.buyerPhone,
      );

      // 2. Initiate SSLCommerz Sandbox Payment
      final gatewayUrl = await _paymentService.initiateSslCommerzPayment(orderWithId);

      if (!context.mounted) return;

      // 3. Open WebView and wait for result
      final result = await Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => SSLCommerzWebViewScreen(url: gatewayUrl),
        ),
      );

      debugPrint('SSLCommerz Payment Result: $result');

      if (result == 'success') {
        // 4. Update order status to paid and reduce stock
        await _orderService.markOrderPaidAndReduceStock(orderId);
        debugPrint('Firestore order $orderId updated to paid and stock reduced.');
        
        // 5. Clear the cart
        await cartProvider.clearCart();
        
        if (!context.mounted) return;
        
        // 6. Navigate to Confirmation Screen
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(
            builder: (context) => OrderConfirmationScreen(order: orderWithId),
          ),
        );
      } else {
        // Payment failed or cancelled
        final status = result == 'cancelled' ? 'cancelled' : 'failed';
        await _orderService.updateOrderStatus(orderId, status);
        debugPrint('Firestore order $orderId updated to $status.');
        
        if (!context.mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(status == 'cancelled' ? 'Payment cancelled.' : 'Payment failed.'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error during checkout: $e')),
      );
    } finally {
      if (mounted) {
        setState(() {
          _isProcessing = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final cartProvider = context.watch<CartProvider>();
    final userProfile = context.watch<UserProvider>().userProfile;

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Text('Checkout', style: GoogleFonts.poppins(color: AppColors.textPrimary, fontWeight: FontWeight.w600)),
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: true,
        iconTheme: const IconThemeData(color: AppColors.textPrimary),
      ),
      body: _isProcessing
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildSectionTitle('Buyer Information'),
                  const SizedBox(height: 12),
                  _buildInfoCard(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _buildInfoRow(Icons.person, userProfile?.name ?? 'No Name'),
                        const SizedBox(height: 12),
                        _buildInfoRow(Icons.email, userProfile?.email ?? 'No Email'),
                        const SizedBox(height: 12),
                        _buildInfoRow(Icons.phone, (userProfile?.phoneNumber.isNotEmpty == true) ? userProfile!.phoneNumber : 'No Phone Number'),
                      ],
                    ),
                  ),
                  const SizedBox(height: 24),
                  
                  _buildSectionTitle('Order Summary'),
                  const SizedBox(height: 12),
                  _buildInfoCard(
                    child: Column(
                      children: [
                        ...cartProvider.items.map((item) => Padding(
                          padding: const EdgeInsets.only(bottom: 12.0),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Expanded(
                                child: Text(
                                  '${item.quantity}x ${item.productName}',
                                  style: GoogleFonts.poppins(fontSize: 14, color: AppColors.textPrimary),
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                              Text(
                                CurrencyFormatter.format(item.price * item.quantity),
                                style: GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w500, color: AppColors.textPrimary),
                              ),
                            ],
                          ),
                        )),
                        const Divider(height: 24),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              'Total Amount',
                              style: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.bold, color: AppColors.textPrimary),
                            ),
                            Text(
                              CurrencyFormatter.format(cartProvider.totalPrice),
                              style: GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.bold, color: AppColors.primary),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 24),

                  _buildSectionTitle('Payment Gateway'),
                  const SizedBox(height: 12),
                  _buildInfoCard(
                    child: SizedBox(
                      width: double.infinity,
                      child: Row(
                        children: [
                          Flexible(
                            flex: 3,
                            child: SingleChildScrollView(
                              scrollDirection: Axis.horizontal,
                              child: Image.network(
                                'https://securepay.sslcommerz.com/public/image/SSLCommerz-Pay-With-logo-All-Size-01.png',
                                height: 40,
                                fit: BoxFit.contain,
                                errorBuilder: (context, error, stackTrace) => const Icon(Icons.payment, size: 40, color: AppColors.primary),
                              ),
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            flex: 2,
                            child: Text(
                              'SSLCommerz (Sandbox)',
                              style: GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w500, color: AppColors.textPrimary),
                              maxLines: 2,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 40),

                  // Pay Now Button
                  SizedBox(
                    width: double.infinity,
                    height: 56,
                    child: ElevatedButton(
                      onPressed: () => _processCheckout(context),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primary,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                      ),
                      child: Text(
                        'Pay Now',
                        style: GoogleFonts.poppins(
                          fontSize: 16,
                          fontWeight: FontWeight.w600,
                          color: AppColors.white,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),
                ],
              ),
            ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: GoogleFonts.poppins(
        fontSize: 18,
        fontWeight: FontWeight.bold,
        color: AppColors.textPrimary,
      ),
    );
  }

  Widget _buildInfoCard({required Widget child}) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: child,
    );
  }

  Widget _buildInfoRow(IconData icon, String text) {
    return Row(
      children: [
        Icon(icon, size: 20, color: AppColors.textSecondary),
        const SizedBox(width: 12),
        Expanded(
          child: Text(
            text,
            style: GoogleFonts.poppins(
              fontSize: 14,
              color: AppColors.textPrimary,
            ),
          ),
        ),
      ],
    );
  }
}
