// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwJFWrCYaVk9I4q8XmHLhtkxv0qO_TkAc',
    appId: '1:918719819899:web:ad65ff01198b6fc05df2de',
    messagingSenderId: '918719819899',
    projectId: 'unimarket-78693',
    authDomain: 'unimarket-78693.firebaseapp.com',
    storageBucket: 'unimarket-78693.firebasestorage.app',
    measurementId: 'G-5P2LPXCRYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATPXQKdnGtonDQ_Yi4EjfdzGgrN3_9400',
    appId: '1:918719819899:android:c5a62f687f3ee7945df2de',
    messagingSenderId: '918719819899',
    projectId: 'unimarket-78693',
    storageBucket: 'unimarket-78693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2P4VYBeTCJNtSIE_DcRxDZEh9eyPGSU',
    appId: '1:918719819899:ios:302eff0e645b18d35df2de',
    messagingSenderId: '918719819899',
    projectId: 'unimarket-78693',
    storageBucket: 'unimarket-78693.firebasestorage.app',
    iosClientId: '918719819899-3btrpaubvl875h75053pvdtkgsu99ga7.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV2P4VYBeTCJNtSIE_DcRxDZEh9eyPGSU',
    appId: '1:918719819899:ios:302eff0e645b18d35df2de',
    messagingSenderId: '918719819899',
    projectId: 'unimarket-78693',
    storageBucket: 'unimarket-78693.firebasestorage.app',
    iosClientId: '918719819899-3btrpaubvl875h75053pvdtkgsu99ga7.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwJFWrCYaVk9I4q8XmHLhtkxv0qO_TkAc',
    appId: '1:918719819899:web:6869359e85e632a75df2de',
    messagingSenderId: '918719819899',
    projectId: 'unimarket-78693',
    authDomain: 'unimarket-78693.firebaseapp.com',
    storageBucket: 'unimarket-78693.firebasestorage.app',
    measurementId: 'G-HSHXVW3MEN',
  );
}
